# Conclusions {#concl}

The initial motivation of this study was to see whether by implementing some of the latest developments in the machine learning and deep learning domains, and in particular, in the deep learning domain, we could yield potential improvements in the forecasting performance of the traditional econometric techniques used in the literature. In order to do that, we introduce a new framework based on the neural network architecture while mantaining the VAR sturcture, which we name Deep VAR. 

Towards this purpose, we compare the fit of the Deep VAR vs. the traditional VAR for monthly US economic data in the period 1959-2021. The results show a persistent and large difference in the performance of the in-sample fit. In particular, the Deep VAR achieves a much lower cumulative loss than the VAR over the entire period for the four analysed time series. This difference aggraviates even more in recession periods, that is, when the time series exhibits non-linear relationships. Hence, reinforcing our inital hypothesis that by modelling the series using neural networks it is possible to capture more complex patterns. 

When it comes to the out-of-sample fit, a priori it may seem that the Deep VAR is expected to overfit the data due to its high number of parameters. Although, the reults clearly show that the Deep VAR achieves a much lower ot-of-sample RMSE than the VAR. We reasoned that this is owed to the regularization applied to the model, the dropout rate and the constraints regarding the neural network architecture. This method guarantees that the Deep VAR does not learn the error of the data in the training stage, and therefore leading to a robust fit for the out-ot-sample performance. 

Policy makers, however, are mainly interested in the forecasting performance of a given model rather than its fit. In this realm, the Deep VAR also performs better than the traditional VAR. In particular, it results in a lower forecasting root mean squared error for each of the analyzed series. To sum up, we can conclude that the Deep VAR outperforms the VAR in every domain explored; the in-sample and out-of-sample fit and the forecasting one. 

The Deep VAR framework has not been introduced in the time series literature, and as any brand new methodology, it leaves a lot of unaswered questions, hence future research on Deep VAR is still missing. In particular, future research should be addressed to develop a methodology to recover standard errors for the point estimates, and therefore, coming up with confidence intervals. Furthermore, exploring a method to be able to create impulse response functions would make of the Deep VAR framework a method as complete as the VAR one, but which has proved to outperfrom in all possible aspects.





