# Introduction

As stated by the European Central Bank, the monetary transmission mechanism is the process through which monetary policy decisions affect the economy in general and the price level in particular. However, the uncertainty of this tramission is huge, given that this transmission is characterized by long, variable and uncertain time lags. Hence, it is difficult to predict how changes in monetary policy actions affect economic real variables. Therefore, it is of foremost importance for policy-makers to come up with tools that allow them to predict these effects.

With this in mind, a lot of research on the forecasting of time series has been developed to asses the effect of current policy decisions on future economic variables. Thanks to this, over the last decades policy makers have had more information when taking decisions. This information can be of the form of point estimates and interval forecasts. To come up with these estimates, several methodologies have been largely applied in the time series forecasting literature. 

Up until now, the most common methodology to come up with these estimates is the so-called Vector Autoregression (VAR). This framework, which belongs to the traditional class of economteric forecasting techniques, has proved to provide policy-makers with fairly good and consistent point and interval estimates. It has therefore been used in the monetary policy divisons of institutions such as the European Central Bank or the International Monetary Fund. 

Simultaneously, with the recent advancement in computational power of computers, and more importantly, the development of more advanced machine learning algorithms and approaches such as deep learning, new algorithms are developed to analyze and forecast time series data. Whereas the good performance of techniques such as VAR is well-known, it is still uncertain whether deep learning algorithms can actually improve these forecasts. 

To this end, this paper aims to provide with a new and ground-breaking methodology that combines the VAR equation-by-equation structure with the deep neural network architecture to capture the potential non-linear relationships in the data generating process. Thereupon, we construct what we called a Deep-VAR framework to generate point and interval forecasts. The ultimate objective of this empirical exercise is to provdie the existing literture with a method that outperforms the most conventional methods, yet keeping interpretability in the underlying mechanism.

To the best of our knowledge, this is the first paper to fit a deep neural network for each equation of the VAR structure. Although a lot of authors have used deep learning to forecast time series, all of them fit the whole system in one big neural network. We believe that by doing it equation-by-equation not only do we maintain interpretabiliy of the model but also we get better forecasting results.

We find that the Deep-VAR methodology outperforms the traditional VAR framework both in-sample and out-of-sample. When it comes to forecasts, we also obtain a lower RMSE. 

Yet, policy makers are not just interested in the forecasting accuracy of the model but they also have an interest in the inference side. For instance, central banks need to know if rates granger cause one variable or not. Another aspect policy makers and researchers are interested in is how the variables of the system evolve through time once a shock takes place. This information is recovered using Impuls Response Functions (IRFs). 

The linear additive relationship of linear models allows the model to observe which variable granger cause another and what are the IRFs of the variables in the system. Unfortunately, in the case of nonlinear models, its nature makes it impossible to recover these insights because the outputs and the inputs do not have a linear additive structure.

Therefore, on the one hand, the nonlinear structure of NN helps us for forecasting in the case that there are nonlinear relationships present in the series, but on the other hand we lose the interpretability of the model, making it impossible to recover IRFs or to even to assess if one variable granger causes another. This problem is also known as the black box problem. This is because the data fed into the input layer passes through the succeeding layers, getting multiplied, added together and transformed in complex and different ways, until it finally arrives, radically transformed, to the output layer. Therefore, it is impossible to assess what happened with one input and how it affected the output.

The rest of the paper is structured as follows: in section 2 we present a literature review of prior research on the methodologies used to provide forecasts and on the monetary trasmission mechanism. Section 3 is a detailed description of the data we use in our empirical exercise. In section 4 we present the traditional VAR methodology and we also present our Deep-VAR model following by our empirical findings in section 5. Finally, in section 6 we finish with concluding remarks. 