---
title: "Deep Vector Autoregression for Macroeconomic Data"
author:
- "Marc Agustí (marc.agusti@barcelonagse.eu)"
- "Patrick Altmeyer (patrick.altmeyer@barcelonagse.eu)"
- "Ignacio Vidal-Quadras Costa (ignacio.vidalquadrascosta@barcelonagse.eu)"
date: "`r format(Sys.Date(), '%B, %Y')`"
output: 
  bookdown::pdf_document2: 
    toc: false
    includes:
      in_header: preamble.tex
      before_body: before_body.tex
  bookdown::html_document2: default
fontsize: 12pt
bibliography: "bib.bib"
link-citations: true
abstract: "Vector autoregression models have been the traditional technique in the last decades when it comes to the forecasting of time series data. In particular, the VAR framework has demonstrated its outperformance in precision and accuracy of predicting the next lags of time series, hence becoming a useful tool for policy makers, whcih rely on this methodology to construct forecasts or even for the analysis of impulse response functions. However, with the recent advancement in computational power of computers, and more importantly, the development of more advanced machine learning algorithms and approaches such as deep learning, new algorithms are developed to analyze and forecast time series data. This paper aims to contribute to the time series literature by using the Long Short-Term Memory (LSTM) to see whether this new advanced methodology is superior to the usual VAR framework. By fitting each regression of the VAR with a neural network instead of with a simple OLS regression, we are able to outperform both in-sample and out-of-sample the predictions of the usual VAR for variables such as GDP, FED funds rate and inflation, ..."
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  out.width = 450,
  fig.align = "center"
)
library(ggplot2)
library(data.table)
library(deepvars)
options(xtable.comment = FALSE)
theme_set(theme_bw())
```

```{r introduction, child="introduction.Rmd"}
```

```{r lit-review, child="lit_review.Rmd"}
```

```{r data, child="data_paper_ig.Rmd"}
```

```{r methodology, child="methodology.Rmd"}
```

```{r empirics, child="empirics.Rmd"}
```

```{r extensions, child="extensions.Rmd"}
```

```{r conclusions, child="conclusions.Rmd"}
```


\FloatBarrier
\pagebreak

# References {-}

<div id="refs"></div>

\pagebreak

```{r annex, child="appendix.Rmd"}
```



