# Literature review {#lit-review}

There is broad agreement among economists on the fact that monetary policy affects economic activity in the short and medium term. @friedman2008monetary found that monetary policy actions are followed by movements in real output that may last for two years or more (@romer1989does; @bernanke1990federal). The underlying forces that trigger these outcomes is of great interest to most economists. Central bankers in particular aim to understand the monetary transmission mechanism. If monetary policy affects the real economy, then what exactly is the transmission mechanism through which these effects occur? This is one of the questions which is among the most important and controversial topics in modern-day macroeconomics.

In the aftermath of the oil price shock in the 1970's, interest emerged in understanding business cycles. To this end economists initially made use of large-scale macroeconomic models, which was criticized by @lucas1976econometric, stating that the assumption of invariant behavioural equations was inconsistent with dynamic maximizing behaviour. Hence, **New Classical** economists started to make use of so-called market clearing models of economic fluctuations. With the goal of really taking into account productivity shocks, **Real Business Cycle** models were developed (@kydland1982time).

Following the failure of large-scale macroeconomic models when trying to predict business cycles, the economic profession resorted to structural vector autoregressive (VAR) models to analyse business cycles, which proved to be useful for capturing the impact of policy actions. @sims1986forecasting suggested that VARs were an efficient tool to evaluate macroeconomic models. One of the advantages of VARs is their simplicity, which makes it easy to estimate and interpret them. 

Yet, this simplicity comes at a cost: conventional VARs are typically not able to capture non-linear relationships in the data, which might be a significant limitation. 
In the very short run many time series can be expected to behave more or less according to their past and a linear model may be efficient to capture dynamics, but for longer term dependencies this is typically not the case. With respect to the economic time series that form part of the monetary transmission mechanism, specifically output, inflation, interest rates and labour market variables, non-linear dependencies are likely to form part of the data generating process as shown by @brock1991nonlinear. This is true in particular during times of abrupt and significant economic fluctuations.

During past years, economists have therefore started to add non-linear techniques to their forecasting tool kit. Machine Learning has contributed a lot to this field of research. Some of the most popular machine learning techniques which do not assume a linear relationship between inputs and outputs include K-Nearest Neighbours (first introduced by @fix1951important), Support Vector Machines (mostly developed by @cortes1995support), Random Forests (first introduced in 1995 by @ho1995random) and Deep Artificial Neural Networks (first proposed in 1943 by @mcculloch1990logical). The latter have been explored previously in the realm of time series forecasting (@hamzaccebi2008improving, @zhang2003time, @kihoro2004seasonal). Neural networks are non-parametric models that have been shown to be particularly successful at capturing non-linearities (@zhang1998forecasting, @zhang2003time).

A particular subclass of neural networks used primarily for sequential data are recurrent neural networks (RNN). RNNs propagate previous outputs recursively allowing the model to learn persistent dependencies and thereby making them very efficient for time series data [@dorffner1996neural]. A recent staff working paper published by the Bank of England provides some empirical support for the argument that deep learning can be successfully applied to macroeconomic data [@joseph2021forecasting]. The authors run a horse race for forecasting inflation across different time horizons comparing the performance of linear and non-linear models. They find that neural networks in particular and also other common machine learning algorithms are useful for forecasting particularly at a longer horizon. 
