---
title: "R Notebook"
output: html_notebook
---

```{r}
library("fbi")
library(ggplot2)
library("ggpubr")
theme_set(
  theme_bw() +
    theme(legend.position = "top")
  )
```

```{r}
test <- fredmd("fredmd/2021-04.csv")
variables <- c("date", "X6", "X25", "X113", "X84")
variables_names <- c("date", "IP", "UR", "CPI", "FFR")
test <- test[3:nrow(test),variables]
colnames(test) <- variables_names
```

X6: Industrial production in first diff of the natural log
X25: Unemployment rate in first diff (NOT UNEMPLOYMENT) 
X113: CPI all items in second diff natural log
X84: Effective federal FED funds in first diff

# Ploting
```{r}
p1 <- ggplot(test, aes(x=date, y=IP)) + geom_line()
p2 <- ggplot(test, aes(x=date, y=UR)) + geom_line()
p3 <- ggplot(test, aes(x=date, y=CPI)) + geom_line()
p4 <- ggplot(test, aes(x=date, y=FFR)) + geom_line()
```

```{r}
figure <- ggarrange(p1, p2, p3, p4,
                    labels = c("A", "B", "C", "D"),
                    ncol = 2, nrow = 2)
figure
```

# Save
```{r}
dt_final <- data.table(test)
saveRDS(dt_final, file = "data_VAR/preprocessed_new.rds")

dt_long <- melt(dt_final, id.vars = "date")
saveRDS(dt_long, file = "data_VAR/preprocessed_tidy_new.rds")
```

